# code: language=ansible
---
- name: Service authelia is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: authelia
    state: started
    enabled: true
# - name: allow authelia port
#   community.general.ufw:
#     rule: allow
#     port: "123456"
